name: 🆙 Bump Patch Version

on:
  push:
    branches:
      - main
    # prevent recursion on commits made by this action
    paths-ignore:
      - '.github/workflows/bump-version.yml'
      - 'version.txt'

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Read current version
        id: getver
        run: |
          VER=$(cat version.txt)
          echo "old=$VER" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          IFS='.' read -r MAJ MIN PATCH <<< "${{ steps.getver.outputs.old }}"
          NEWPATCH=$((PATCH + 1))
          echo "${MAJ}.${MIN}.${NEWPATCH}" > version.txt
          echo "new=${MAJ}.${MIN}.${NEWPATCH}" >> $GITHUB_OUTPUT

      - name: Commit & push version bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new }}"
          git push origin main
