name: 🆙 Bump Version (patch with rollover)

on:
  push:
    branches:
      - main
    # don’t retrigger when bumping version.txt itself
    paths-ignore:
      - '.github/workflows/bump-version.yml'
      - 'version.txt'

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Read current version
        id: getver
        run: |
          VER=$(cat version.txt)
          echo "old=$VER" >> $GITHUB_OUTPUT

      - name: Compute next version
        id: bump
        run: |
          IFS='.' read -r MAJ MIN PATCH <<< "${{ steps.getver.outputs.old }}"
          if [ "$PATCH" -ge 9 ]; then
            PATCH=0
            MIN=$((MIN + 1))
          else
            PATCH=$((PATCH + 1))
          fi
          NEW="${MAJ}.${MIN}.${PATCH}"
          echo "$NEW" > version.txt
          echo "new=$NEW" >> $GITHUB_OUTPUT

      - name: Commit & push version bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new }}"
          git push origin main
